### ISSUE TITLE
Missing space in the title

### ISSUE THREAD

**Issue by RandomKuchen** [spicetify/marketplace#773] opened 2024-05-31 19:47 UTC
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify für Windows (64 Bit)
1.2.38.720.ga4a70a0e
Spicetify v2.36.11
```

### 📝 Description

hey! 

On the landing page is a space missing on the top left. I tried a few different versions of the marketplace but none of these fix this. 
I tried the automatic installed version, which I assume is the latest (currently 1.0.2), 1.0.1 and 1.0. 
I guess Spotify messed something up.  

### 📸 Screenshots

![grafik](https://github.com/spicetify/marketplace/assets/63271030/e05c7a70-d3d8-4f69-876d-46a2afd8cd5a)

**Comment by rxri** [comment] 2024-05-31 19:48
Duplicate of https://github.com/spicetify/marketplace/issues/767

**Closed by rxri** 2024-05-31 19:48 UTC
Labels: 🐛 bug
